"""Generation of a standalone GEMSEO script from a project (SPEC § 10).

The script reads top to bottom: docstring, imports, constants, then one short
function per step. For a model or an MDA driver:

- ``build_disciplines()`` creates the disciplines;
- ``build_process()`` combines them in a chain or an MDA;
- ``main()`` runs the process and prints its outputs.

The runner (plan 17) imports the script and calls ``build_process()``; the
mapping from discipline names to diagram nodes is returned separately, so the
script itself contains nothing but GEMSEO code.
"""

import json
import textwrap
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

from gemseo_process_builder import __version__
from gemseo_process_builder.codegen.context import CodegenContext
from gemseo_process_builder.codegen.context import CodegenError
from gemseo_process_builder.codegen.disciplines import Block
from gemseo_process_builder.codegen.literals import literal
from gemseo_process_builder.codegen.naming import to_identifier
from gemseo_process_builder.codegen.pretty import LINE_LENGTH
from gemseo_process_builder.codegen.pretty import Call
from gemseo_process_builder.codegen.pretty import DictExpr
from gemseo_process_builder.codegen.pretty import Expr
from gemseo_process_builder.codegen.pretty import ListExpr
from gemseo_process_builder.codegen.pretty import Raw
from gemseo_process_builder.codegen.pretty import returning
from gemseo_process_builder.codegen.pretty import statement
from gemseo_process_builder.codegen.pretty import string
from gemseo_process_builder.codegen.structure import children_disciplines
from gemseo_process_builder.codegen.structure import is_supported_target
from gemseo_process_builder.codegen.structure import process_expression
from gemseo_process_builder.codegen.writer import Function
from gemseo_process_builder.codegen.writer import ModuleWriter
from gemseo_process_builder.core.model import AssemblyNode
from gemseo_process_builder.core.model import ComponentNode
from gemseo_process_builder.core.model import ContainerNode
from gemseo_process_builder.core.model import DriverNode
from gemseo_process_builder.core.model import Project
from gemseo_process_builder.core.model import iter_nodes
from gemseo_process_builder.core.resolver import PortRef
from gemseo_process_builder.core.resolver import resolve

__all__ = ["CodegenError", "GeneratedScript", "generate", "script_file_name"]


@dataclass
class GeneratedScript:
    """A generated script and what the runner needs to know about it."""

    source: str
    mapping: dict[str, Any]
    """``{"target": node id, "kind": "process", "disciplines": {node id: name}}``."""

    def mapping_json(self) -> str:
        """The content of the ``*.gpb-map.json`` sidecar file."""
        return json.dumps(self.mapping, indent=2, sort_keys=True) + "\n"


def script_file_name(project: Project, target_id: str) -> str:
    """A file name like ``sellar_optimizer.py``."""
    target = project.find(target_id)
    parts = [to_identifier(project.metadata.name)]
    if target is not None and target.id != project.root.id:
        parts.append(to_identifier(target.name))
    return "_".join(part for part in parts if part) + ".py"


def generate(
    project: Project,
    target_id: str | None = None,
    project_file: str = "",
    today: date | None = None,
) -> GeneratedScript:
    """Generate the script running a target of a project.

    Args:
        project: The project.
        target_id: The node to run: the root model, an assembly or an MDA
            driver; the root by default.
        project_file: The project file name, cited in the docstring.
        today: The generation date (fixed in tests).

    Raises:
        CodegenError: When the project cannot be generated.
    """
    target = project.find(target_id or project.root.id)
    if not isinstance(target, AssemblyNode | DriverNode):
        msg = "Only the model, an assembly or a driver can be run."
        raise CodegenError(msg)
    if isinstance(target, DriverNode) and not is_supported_target(target):
        msg = f"{target.name}: {target.kind} drivers cannot be generated yet."
        raise CodegenError(msg)
    if not target.children:
        msg = f"{target.name} is empty: add components first."
        raise CodegenError(msg)

    file_name = script_file_name(project, target.id)
    title = project.metadata.name
    if target.id != project.root.id:
        title += f": {target.name}"
    source_note = f" from {project_file}" if project_file else ""
    origin = textwrap.fill(
        f"Generated by GEMSEO Process Builder {__version__}{source_note} "
        f"on {(today or date.today()).isoformat()}.",
        LINE_LENGTH,
    )
    writer = ModuleWriter(f"{title}.\n\n{origin}\nRun it with: python {file_name}")
    context = CodegenContext(project, resolve(project), writer)
    context.names.taken.update({"build_disciplines", "build_process", "main"})

    block = Block()
    variables = children_disciplines(context, target, block)
    discipline = writer.use("gemseo.core.discipline", "Discipline")
    writer.functions.insert(
        0,
        Function(
            f"def build_disciplines() -> list[{discipline}]:",
            f"Create the disciplines of {target.name}.",
            block.header() + block.lines + [f"    return [{', '.join(variables)}]"],
        ),
    )
    expression, comment = process_expression(
        context, target, Raw("build_disciplines()")
    )
    writer.functions.append(
        Function(
            f"def build_process() -> {discipline}:",
            f"Combine the disciplines of {target.name} into one process.",
            comment + returning(expression),
        )
    )
    configure_logger = writer.use("gemseo", "configure_logger")
    body = [f"    {configure_logger}()", "    process = build_process()"]
    input_data = input_values(context, target)
    if input_data is None:
        body.append("    results = process.execute()")
    else:
        body.append(
            "    # The input values set in the diagram; the others keep their default."
        )
        body.extend(statement("input_data", input_data))
        body.append("    results = process.execute(input_data)")
    body += [
        "    for name, value in sorted(results.items()):",
        '        print(f"{name} = {value}")',
    ]
    writer.functions.append(
        Function(
            "def main() -> None:",
            "Run the process and print the results.",
            body,
        )
    )
    return GeneratedScript(
        writer.source(),
        {"target": target.id, "kind": "process", "disciplines": context.mapping},
    )


def input_values(context: CodegenContext, target: ContainerNode) -> DictExpr | None:
    """The input values typed in the diagram, or ``None`` if there are none.

    Only the inputs that no discipline of the target computes are given.
    """
    components = [
        node for node, _ in iter_nodes(target) if isinstance(node, ComponentNode)
    ]
    ports = context.resolution.ports
    computed = {
        ports[PortRef(node.id, port.local_name, "out")].global_name
        for node in components
        for port in node.ports
        if port.direction == "out"
    }
    values: dict[str, Expr] = {}
    for node in components:
        for port in node.ports:
            if port.direction != "in" or port.default_text is None:
                continue
            name = ports[PortRef(node.id, port.local_name, "in")].global_name
            if name not in computed and name not in values:
                values[name] = _array(context, port.default, port.default_text)
    if not values:
        return None
    return DictExpr([(string(name), value) for name, value in sorted(values.items())])


def _array(context: CodegenContext, value: Any, text: str) -> Expr:
    """A NumPy array literal: GEMSEO exchanges numbers as arrays."""
    if isinstance(value, str | bool) or value is None:
        return literal(value)
    array = context.writer.use("numpy", "array")
    items = value if isinstance(value, list) else [value]
    texts = [text] if not isinstance(value, list) else [None] * len(items)
    elements = [
        literal(item, item_text) for item, item_text in zip(items, texts, strict=True)
    ]
    return Call(array, [("", ListExpr(elements))])


def write_script(script: GeneratedScript, path: Path) -> None:
    """Write a script and its mapping sidecar (``<name>.gpb-map.json``)."""
    path.write_text(script.source, encoding="utf-8", newline="\n")
    path.with_suffix(".gpb-map.json").write_text(
        script.mapping_json(), encoding="utf-8", newline="\n"
    )
