"""Projects saved as GEMSEO scripts: merging the code of the user, paths."""

from pathlib import Path

from builders import component
from builders import driver
from builders import project
from golden_projects import example

from gemseo_process_builder.codegen.generator import generate
from gemseo_process_builder.codegen.generator import project_script
from gemseo_process_builder.codegen.generator import project_target
from gemseo_process_builder.core.script_project import merge_script

GENERATED = generate(example("sellar_mdf"), "n-optimizer").source


def test_the_code_added_by_the_user_is_kept() -> None:
    existing = GENERATED.replace(
        'if __name__ == "__main__":',
        "import json\n\n\n"
        "# My post-processing.\n"
        "def summary(scenario):\n"
        "    return json.dumps(scenario.optimization_result.x_opt.tolist())\n\n\n"
        "THRESHOLD = 3.0\n\n\n"
        'if __name__ == "__main__":',
    )
    merged = merge_script(GENERATED, existing)
    assert (merged.kept, merged.replaced) == (["summary"], False)
    source = merged.source
    assert "import json\n" in source
    assert "# My post-processing.\ndef summary(scenario):" in source
    assert "THRESHOLD = 3.0" in source
    # Before the functions of the application, once each.
    assert source.index("def summary") < source.index("def build_disciplines")
    assert source.count("def build_scenario") == 1
    assert source.count('if __name__ == "__main__":') == 1
    compile(source, "sellar.py", "exec")
    # Saving again changes nothing.
    assert merge_script(GENERATED, source).source == source


def test_a_script_written_by_hand_keeps_its_definitions_only() -> None:
    existing = (
        '"""My study."""\n'
        "from gemseo import create_scenario\n\n\n"
        "def area(span=1.0):\n    area = span\n    return area\n\n\n"
        "scenario = create_scenario([], 'area', None)\n"
        "scenario.execute(algo_name='SLSQP')\n"
    )
    merged = merge_script(GENERATED, existing)
    assert (merged.kept, merged.replaced) == (["area"], True)
    assert "def area(span=1.0):" in merged.source
    assert "scenario.execute(algo_name='SLSQP')" not in merged.source
    assert merge_script(GENERATED, "def (").replaced


def test_the_script_of_a_project_uses_its_own_definitions(tmp_path: Path) -> None:
    script = tmp_path / "wing.py"
    function = component("Area", ["span"], ["area"], kind="python_function")
    function.config = {"module_path": str(script), "function": "wing_area"}
    elsewhere = component("Lift", ["area"], ["lift"], kind="python_function")
    elsewhere.config = {"module_path": str(tmp_path / "lift.py"), "function": "lift"}
    p = project(function, elsewhere)
    assert project_target(p) == p.root.id
    source = project_script(p, script)
    assert "AutoPyDiscipline(wing_area, " in source
    assert "Run it with: python wing.py" in source
    assert "from wing import" not in source  # Not imported from itself.
    assert "from lift import lift" in source
    single = project(driver("Opt", "optimization", component("A", ["x"], ["y"])))
    assert project_target(single) == "n-Opt"


def test_the_files_next_to_the_script_are_found_from_it(tmp_path: Path) -> None:
    script = tmp_path / "study.py"
    wrapper = component("Solver", ["x"], ["y"], kind="executable")
    wrapper.config = {
        "descriptor_path": str(tmp_path / "tools" / "solver.gpbwrap.json")
    }
    source = project_script(project(wrapper), script)
    assert (
        'SOLVER_WRAPPER = Path(__file__).parent / "tools/solver.gpbwrap.json"' in source
    )
    # Written again at each save, not kept as code of the user.
    edited = source.replace("tools/solver", "other/solver")
    assert merge_script(source, edited).source == source


def test_the_docstring_holds_the_name_and_description(tmp_path: Path) -> None:
    study = example("sellar_mdf")
    study.metadata.name = "Wing"
    study.metadata.description = "Sizing of a wing."
    source = project_script(study, tmp_path / "wing.py")
    assert source.startswith('"""Wing.\n\nSizing of a wing.\n\nGenerated by')
    assert " from " not in source.split("\n")[4]
