"""Panel cost.

Generated by GEMSEO Process Builder 0.1.0 from analytic_chain.gpb.json on 2026-01-01.
Run it with: python panel_cost.py
"""

from gemseo import configure_logger
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from numpy import array


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    area = AnalyticDiscipline({"area": "length*width"}, name="Area")
    # The values typed in the diagram replace the default input values.
    area.default_input_data.update({"length": array([2.0]), "width": array([1e-1])})
    cost = AnalyticDiscipline({"cost": "12.5*area + 3"}, name="Cost")
    return [area, cost]


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
