"""External code.

Generated by GEMSEO Process Builder 0.1.0 from external_code.gpb.json on 2026-01-01.
Run it with: python external_code.py
"""

from pathlib import Path

from gemseo import configure_logger
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline

from gemseo_process_builder.runtime.executable import ExecutableDiscipline

SOLVER_WRAPPER = Path("solver.gpbwrap.json")


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    # Solver runs an external code described by its wrapper.
    solver = ExecutableDiscipline.from_descriptor(SOLVER_WRAPPER)
    # External codes give no derivatives: they are approximated by finite
    # differences.
    solver.set_jacobian_approximation()
    return [solver]


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
