"""Masses.

Generated by GEMSEO Process Builder 0.1.0 from isolated_instances.gpb.json on
2026-01-01.
Run it with: python masses.py
"""

from gemseo import configure_logger
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.disciplines.remapping import RemappingDiscipline
from numpy import array


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    front = AnalyticDiscipline({"mass": "density*volume"}, name="Front")
    # RemappingDiscipline gives variables the names used by the other
    # disciplines; it lists every variable, renamed or not.
    # Front exchanges volume as Front:volume, mass as Front:mass.
    front = RemappingDiscipline(
        front,
        input_mapping={"density": "density", "Front:volume": "volume"},
        output_mapping={"Front:mass": "mass"},
    )
    rear = AnalyticDiscipline({"mass": "density*volume"}, name="Rear")
    # Rear exchanges volume as Rear:volume, mass as Rear:mass.
    rear = RemappingDiscipline(
        rear,
        input_mapping={"density": "density", "Rear:volume": "volume"},
        output_mapping={"Rear:mass": "mass"},
    )
    total_mass = AnalyticDiscipline(
        {"total_mass": "front_mass + rear_mass"}, name="TotalMass"
    )
    # TotalMass exchanges front_mass as Front:mass, rear_mass as Rear:mass.
    total_mass = RemappingDiscipline(
        total_mass,
        input_mapping={"Front:mass": "front_mass", "Rear:mass": "rear_mass"},
        output_mapping={"total_mass": "total_mass"},
    )
    return [front, rear, total_mass]


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    # The input values set in the diagram; the others keep their default.
    input_data = {
        "Front:volume": array([2.5]),
        "Rear:volume": array([1.5]),
        "density": array([7800]),
    }
    results = process.execute(input_data)
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
