"""Aircraft.

Generated by GEMSEO Process Builder 0.1.0 from parallel_assembly.gpb.json on 2026-01-01.
Run it with: python aircraft.py
"""

from gemseo import configure_logger
from gemseo.core.chains.chain import MDOChain
from gemseo.core.chains.parallel_chain import MDOParallelChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    wings = build_wings()
    total_lift = AnalyticDiscipline(
        {"lift": "lift_left + lift_right"}, name="TotalLift"
    )
    return [wings, total_lift]


def build_wings() -> Discipline:
    """Create the Wings assembly."""
    left_wing = AnalyticDiscipline({"lift_left": "0.5*span"}, name="LeftWing")
    right_wing = AnalyticDiscipline({"lift_right": "0.5*span"}, name="RightWing")
    # These disciplines do not depend on each other: they run in parallel.
    return MDOParallelChain([left_wing, right_wing], name="Wings")


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
