"""Thermal stress.

Generated by GEMSEO Process Builder 0.1.0 from remapped_link.gpb.json on 2026-01-01.
Run it with: python thermal_stress.py
"""

from gemseo import configure_logger
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.disciplines.remapping import RemappingDiscipline


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    source = AnalyticDiscipline({"temperature": "300 + 2*x"}, name="Source")
    sink = AnalyticDiscipline({"stress": "0.01*t_in"}, name="Sink")
    # RemappingDiscipline gives variables the names used by the other
    # disciplines; it lists every variable, renamed or not.
    # Sink exchanges t_in as temperature.
    sink = RemappingDiscipline(
        sink, input_mapping={"temperature": "t_in"}, output_mapping={"stress": "stress"}
    )
    # GEMSEO 6 cannot differentiate a discipline whose inputs are renamed:
    # its derivatives are approximated by finite differences.
    sink.set_jacobian_approximation()
    return [source, sink]


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
