"""Rosenbrock surrogate: Optimizer.

Generated by GEMSEO Process Builder 0.1.0 from rosenbrock_surrogate.gpb.json on
2026-01-01.
Run it with: python rosenbrock_surrogate_optimizer.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario, from_pickle
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.disciplines.surrogate import SurrogateDiscipline
from gemseo.scenarios.mdo_scenario import MDOScenario

ROSENBROCK_MODEL = Path("rosenbrock_surrogate.surrogates/Rosenbrock.pkl")


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Optimizer."""
    # A surrogate is a regression model trained on the results of a DOE:
    # fast to evaluate, and accurate inside the ranges it was trained on.
    # Surrogate: RBFRegressor trained on 30 samples of the run
    # r-20260925-100000: (x, y) -> (f).
    surrogate = SurrogateDiscipline(from_pickle(ROSENBROCK_MODEL))
    surrogate.name = "Surrogate"
    return [surrogate]


def build_design_space() -> DesignSpace:
    """Define the variables the optimizer is allowed to change."""
    design_space = create_design_space()
    design_space.add_variable("x", lower_bound=-2.0, upper_bound=2.0, value=0.0)
    design_space.add_variable("y", lower_bound=-2.0, upper_bound=2.0, value=0.0)
    return design_space


def build_scenario() -> MDOScenario:
    """Set up the optimization problem."""
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other at each iteration.
    scenario = create_scenario(
        build_disciplines(),
        "f",
        build_design_space(),
        name="Optimizer",
        formulation_name="DisciplinaryOpt",
    )
    return scenario


def execute_scenario(scenario: MDOScenario) -> None:
    """Run the SLSQP optimizer for at most 50 iterations."""
    scenario.execute(algo_name="SLSQP", max_iter=50)


def main() -> None:
    """Run the optimization and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
