"""Sellar IDF: Optimizer.

Generated by GEMSEO Process Builder 0.1.0 from sellar_idf.gpb.json on 2026-01-01.
Run it with: python sellar_idf_optimizer.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.problems.mdo.sellar.sellar_1 import Sellar1
from gemseo.problems.mdo.sellar.sellar_2 import Sellar2
from gemseo.problems.mdo.sellar.sellar_system import SellarSystem
from gemseo.scenarios.mdo_scenario import MDOScenario


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Optimizer."""
    sellar1 = Sellar1()
    sellar2 = Sellar2()
    sellar_system = SellarSystem()
    return [sellar1, sellar2, sellar_system]


def build_design_space() -> DesignSpace:
    """Define the variables the optimizer is allowed to change."""
    design_space = create_design_space()
    design_space.add_variable("x_1", lower_bound=0.0, upper_bound=10.0, value=1.0)
    design_space.add_variable("x_2", lower_bound=0.0, upper_bound=10.0, value=1.0)
    design_space.add_variable(
        "x_shared", size=2, lower_bound=[-10.0, 0.0], upper_bound=10.0, value=[4.0, 3.0]
    )
    design_space.add_variable("y_1", lower_bound=-100.0, upper_bound=100.0, value=1.0)
    design_space.add_variable("y_2", lower_bound=-100.0, upper_bound=100.0, value=1.0)
    return design_space


def build_scenario() -> MDOScenario:
    """Set up the optimization problem."""
    # IDF formulation: the optimizer also sets the coupling variables and
    # adds constraints making them consistent, so no MDA is needed.
    scenario = create_scenario(
        build_disciplines(),
        "obj",
        build_design_space(),
        name="Optimizer",
        formulation_name="IDF",
    )
    scenario.add_constraint("c_1", constraint_type="ineq")
    scenario.add_constraint("c_2", constraint_type="ineq")
    return scenario


def execute_scenario(scenario: MDOScenario) -> None:
    """Run the SLSQP optimizer for at most 100 iterations."""
    scenario.execute(algo_name="SLSQP", max_iter=100)


def main() -> None:
    """Run the optimization and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
