"""Sellar: SellarMDA.

Generated by GEMSEO Process Builder 0.1.0 from sellar_mda.gpb.json on 2026-01-01.
Run it with: python sellar_sellar_mda.py
"""

from gemseo import configure_logger, create_mda
from gemseo.core.discipline import Discipline
from gemseo.problems.mdo.sellar.sellar_1 import Sellar1
from gemseo.problems.mdo.sellar.sellar_2 import Sellar2
from gemseo.problems.mdo.sellar.sellar_system import SellarSystem


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of SellarMDA."""
    sellar1 = Sellar1()
    sellar2 = Sellar2()
    sellar_system = SellarSystem()
    return [sellar1, sellar2, sellar_system]


def build_process() -> Discipline:
    """Combine the disciplines of SellarMDA into one process."""
    # An MDA solves the coupling loop between Sellar1 and Sellar2 (y_1, y_2).
    return create_mda("MDAChain", build_disciplines(), tolerance=1e-10, max_mda_iter=50)


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
