"""Sellar MDF: Optimizer.

Generated by GEMSEO Process Builder 0.1.0 from sellar_mdf_colored.gpb.json on
2026-01-01.
Run it with: python sellar_mdf_optimizer.py
"""

import sys
from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.problems.mdo.sellar.sellar_1 import Sellar1
from gemseo.problems.mdo.sellar.sellar_2 import Sellar2
from gemseo.problems.mdo.sellar.sellar_system import SellarSystem
from gemseo.scenarios.mdo_scenario import MDOScenario

NODE_FOLDER = Path(".")


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Optimizer."""
    sellar1 = Sellar1()
    sellar2 = Sellar2()
    sellar_system = SellarSystem()
    return [sellar1, sellar2, sellar_system]


def build_design_space() -> DesignSpace:
    """Define the variables the optimizer is allowed to change."""
    design_space = create_design_space()
    design_space.add_variable("x_1", lower_bound=0.0, upper_bound=10.0, value=1.0)
    design_space.add_variable("x_2", lower_bound=0.0, upper_bound=10.0, value=1.0)
    design_space.add_variable(
        "x_shared", size=2, lower_bound=[-10.0, 0.0], upper_bound=10.0, value=[4.0, 3.0]
    )
    return design_space


def build_scenario() -> MDOScenario:
    """Set up the optimization problem."""
    # MDF formulation: an MDA solves the coupling loop between
    # Sellar1 and Sellar2 (y_1, y_2) at each iteration.
    scenario = create_scenario(
        build_disciplines(),
        "obj",
        build_design_space(),
        name="Optimizer",
        formulation_name="MDF",
        main_mda_name="MDAGaussSeidel",
    )
    scenario.add_constraint("c_1", constraint_type="ineq")
    scenario.add_constraint("c_2", constraint_type="ineq")
    return scenario


def execute_scenario(scenario: MDOScenario) -> None:
    """Run the LSO_GCMMA optimizer for at most 100 iterations."""
    # The modules of this project are imported from their folder.
    sys.path.insert(0, str(NODE_FOLDER))
    from sellar_pattern import sellar_pattern

    # The optimizer takes the gradients of the constraints from a few
    # tens of directional derivatives, grouping the variables that never
    # share a constraint; the pattern function says which ones do.
    scenario.execute(
        algo_name="LSO_GCMMA",
        max_iter=100,
        jacobian_mode="hybrid",
        sparsity_pattern=sellar_pattern,
    )


def main() -> None:
    """Run the optimization and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
