"""Plate stress.

Generated by GEMSEO Process Builder 0.1.0 from units_conversion.gpb.json on 2026-01-01.
Run it with: python plate_stress.py
"""

from gemseo import configure_logger
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.disciplines.linear_combination import LinearCombination
from gemseo.disciplines.remapping import RemappingDiscipline
from numpy import array


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    plate = AnalyticDiscipline(
        {"thickness": "0.1*width", "temperature": "20 + 0*width"}, name="Plate"
    )
    # The values typed in the diagram replace the default input values.
    plate.default_input_data.update({"width": array([10.0])})
    # A conversion discipline passes a value on in the unit its users
    # expect: converted = factor * value + offset.
    # Plate gives thickness in mm, used in m.
    convert_thickness_mm_to_m = LinearCombination(
        input_names=["thickness"],
        output_name="thickness_m",
        input_coefficients={"thickness": 0.001},
    )
    convert_thickness_mm_to_m.name = "convert_thickness_mm_to_m"
    # Plate gives temperature in degC, used in K.
    convert_temperature_deg_c_to_k = LinearCombination(
        input_names=["temperature"],
        output_name="temperature_k",
        input_coefficients={"temperature": 1.0},
        offset=273.15,
    )
    convert_temperature_deg_c_to_k.name = "convert_temperature_deg_c_to_k"
    stress = AnalyticDiscipline(
        {"stress": "1000*thickness + temperature"}, name="Stress"
    )
    # RemappingDiscipline gives variables the names used by the other
    # disciplines; it lists every variable, renamed or not.
    # Stress exchanges thickness as thickness_m, temperature as temperature_k.
    stress = RemappingDiscipline(
        stress,
        input_mapping={"thickness_m": "thickness", "temperature_k": "temperature"},
        output_mapping={"stress": "stress"},
    )
    # GEMSEO 6 cannot differentiate a discipline whose inputs are renamed:
    # its derivatives are approximated by finite differences.
    stress.set_jacobian_approximation()
    return [plate, convert_thickness_mm_to_m, convert_temperature_deg_c_to_k, stress]


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
