"""Beam chain.

Beam chain: the section, the loads, the stress and the mass of a cantilever beam,
computed one after the other by an assembly run as a chain, in order. A DOE varies the
width and the height of the section.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python beam_chain.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.scenarios.doe_scenario import DOEScenario
from numpy import array


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Study."""
    beam = build_beam()
    return [beam]


def build_beam() -> Discipline:
    """Create the Beam assembly."""
    section = AnalyticDiscipline(
        {"area": "width*height", "inertia": "width*height**3/12"}, name="Section"
    )
    loads = AnalyticDiscipline({"moment": "tip_load*length"}, name="Loads")
    # The values typed in the diagram replace the default input values.
    loads.default_input_data.update({"length": array([2]), "tip_load": array([10000])})
    stress = AnalyticDiscipline(
        {"stress_mpa": "moment*(height/2)/inertia/1e6"}, name="Stress"
    )
    mass = AnalyticDiscipline({"mass_kg": "7850*area*length"}, name="Mass")
    mass.default_input_data.update({"length": array([2])})
    # The disciplines run one after the other, in this order.
    return MDOChain([section, loads, stress, mass], name="Beam")


def build_design_space() -> DesignSpace:
    """Define the variables the study makes vary, with their bounds."""
    design_space = create_design_space()
    design_space.add_variable("width", lower_bound=0.05, upper_bound=0.2)
    design_space.add_variable("height", lower_bound=0.1, upper_bound=0.4)
    return design_space


def build_scenario() -> DOEScenario:
    """Set up the design of experiments."""
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other for each sample.
    scenario = create_scenario(
        build_disciplines(),
        "stress_mpa",
        build_design_space(),
        name="Study",
        scenario_type="DOE",
        formulation_name="DisciplinaryOpt",
    )
    scenario.add_observable("mass_kg")
    return scenario


def execute_scenario(scenario: DOEScenario) -> None:
    """Evaluate the model at 20 points chosen by LHS."""
    scenario.execute(algo_name="LHS", n_samples=20, seed=1)


def main() -> None:
    """Run the study and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
