"""Sellar DOE around optimization.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python doe_around_optimization.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.disciplines.scenario_adapters.mdo_scenario_adapter import MDOScenarioAdapter
from gemseo.problems.mdo.sellar.sellar_1 import Sellar1
from gemseo.problems.mdo.sellar.sellar_2 import Sellar2
from gemseo.problems.mdo.sellar.sellar_system import SellarSystem
from gemseo.scenarios.doe_scenario import DOEScenario
from gemseo.scenarios.mdo_scenario import MDOScenario


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Study."""
    optimizer = build_optimizer_adapter()
    return [optimizer]


def build_optimizer_adapter() -> MDOScenarioAdapter:
    """Wrap Optimizer into a discipline of Study."""
    # The adapter runs the whole optimization each time it is executed:
    # it sets the inputs listed first, then gives back the outputs listed
    # second.
    return MDOScenarioAdapter(
        build_optimizer_scenario(),
        ["alpha"],
        ["obj", "x_1", "x_shared"],
        reset_x0_before_opt=True,
    )


def build_optimizer_scenario() -> MDOScenario:
    """Set up Optimizer, the optimization run by Study."""
    sellar1 = Sellar1()
    sellar2 = Sellar2()
    sellar_system = SellarSystem()
    design_space = create_design_space()
    design_space.add_variable("x_1", lower_bound=0.0, upper_bound=10.0, value=1.0)
    design_space.add_variable("x_2", lower_bound=0.0, upper_bound=10.0, value=1.0)
    design_space.add_variable(
        "x_shared", size=2, lower_bound=[-10.0, 0.0], upper_bound=10.0, value=[4.0, 3.0]
    )
    # MDF formulation: an MDA solves the coupling loop between
    # Sellar1 and Sellar2 (y_1, y_2) at each iteration.
    scenario = create_scenario(
        [sellar1, sellar2, sellar_system],
        "obj",
        design_space,
        name="Optimizer",
        formulation_name="MDF",
        main_mda_name="MDAGaussSeidel",
    )
    scenario.add_constraint("c_1", constraint_type="ineq")
    scenario.add_constraint("c_2", constraint_type="ineq")
    # A nested scenario runs with the algorithm set here each time its
    # parent executes it.
    scenario.set_algorithm(algo_name="SLSQP", max_iter=30)
    return scenario


def build_design_space() -> DesignSpace:
    """Define the variables the study makes vary, with their bounds."""
    design_space = create_design_space()
    design_space.add_variable("alpha", lower_bound=3.0, upper_bound=4.0, value=3.16)
    return design_space


def build_scenario() -> DOEScenario:
    """Set up the design of experiments."""
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other for each sample.
    scenario = create_scenario(
        build_disciplines(),
        "obj",
        build_design_space(),
        name="Study",
        scenario_type="DOE",
        formulation_name="DisciplinaryOpt",
    )
    scenario.add_observable("x_1")
    scenario.add_observable("x_shared")
    return scenario


def execute_scenario(scenario: DOEScenario) -> None:
    """Evaluate the model at 5 points chosen by LHS."""
    scenario.execute(algo_name="LHS", n_samples=5, seed=1)


def main() -> None:
    """Run the study and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
