"""Optimization sequence.

Optimization sequence: a chain runs the material data, then the optimization of a beam
(the lightest section under the allowable stress), then its cost.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python optimization_sequence.py
"""

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.core.chains.chain import MDOChain
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.disciplines.scenario_adapters.mdo_scenario_adapter import MDOScenarioAdapter
from gemseo.scenarios.mdo_scenario import MDOScenario
from numpy import array


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Model."""
    material = AnalyticDiscipline({"allowable_mpa": "yield_mpa/1.5"}, name="Material")
    # The values typed in the diagram replace the default input values.
    material.default_input_data.update({"yield_mpa": array([355])})
    optimizer = build_optimizer_adapter()
    cost = AnalyticDiscipline({"cost_eur": "2.5*mass_kg"}, name="Cost")
    return [material, optimizer, cost]


def build_optimizer_adapter() -> MDOScenarioAdapter:
    """Wrap Optimizer into a discipline of Model."""
    # The adapter runs the whole optimization each time it is executed:
    # it sets the inputs listed first, then gives back the outputs listed
    # second.
    return MDOScenarioAdapter(
        build_optimizer_scenario(), ["allowable_mpa"], ["mass_kg"]
    )


def build_optimizer_scenario() -> MDOScenario:
    """Set up Optimizer, the optimization run by Model."""
    section = AnalyticDiscipline(
        {"area": "width*height", "inertia": "width*height**3/12"}, name="Section"
    )
    section.default_input_data.update({"width": array([0.1]), "height": array([0.2])})
    stress = AnalyticDiscipline(
        {"margin_mpa": "tip_load*length*(height/2)/inertia/1e6 - allowable_mpa"},
        name="Stress",
    )
    stress.default_input_data.update(
        {"height": array([0.2]), "tip_load": array([50000]), "length": array([2])}
    )
    mass = AnalyticDiscipline({"mass_kg": "7850*area*length"}, name="Mass")
    mass.default_input_data.update({"length": array([2])})
    design_space = create_design_space()
    design_space.add_variable("width", lower_bound=0.05, upper_bound=0.3, value=0.15)
    design_space.add_variable("height", lower_bound=0.1, upper_bound=0.5, value=0.3)
    # MDF formulation: the disciplines are evaluated in order at each iteration.
    scenario = create_scenario(
        [section, stress, mass],
        "mass_kg",
        design_space,
        name="Optimizer",
        formulation_name="MDF",
    )
    scenario.add_constraint("margin_mpa", constraint_type="ineq")
    # A nested scenario runs with the algorithm set here each time its
    # parent executes it.
    scenario.set_algorithm(algo_name="SLSQP", max_iter=50)
    return scenario


def build_process() -> Discipline:
    """Combine the disciplines of Model into one process."""
    # The disciplines run one after the other, in this order.
    return MDOChain(build_disciplines(), name="Model")


def main() -> None:
    """Run the process and print the results."""
    configure_logger()
    process = build_process()
    results = process.execute()
    for name, value in sorted(results.items()):
        print(f"{name} = {value}")


if __name__ == "__main__":
    main()
