"""Rosenbrock parametric study.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python rosenbrock_parametric.py
"""

from itertools import product
from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.scenarios.doe_scenario import DOEScenario
from numpy import array, float64, linspace
from numpy.typing import NDArray


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Study."""
    rosenbrock = AnalyticDiscipline(
        {"f": "(1 - x)**2 + 100*(y - x**2)**2"}, name="Rosenbrock"
    )
    return [rosenbrock]


def build_design_space() -> DesignSpace:
    """Define the variables the study makes vary, with their bounds."""
    design_space = create_design_space()
    design_space.add_variable("x", lower_bound=-2.0, upper_bound=2.0)
    design_space.add_variable("y", lower_bound=0.0, upper_bound=2.0)
    return design_space


def build_samples() -> NDArray[float64]:
    """List every combination of the values, one row per evaluation."""
    x_values = linspace(-2.0, 2.0, 5)
    y_values = [0.0, 1.0, 2.0]
    return array(list(product(x_values, y_values)))


def build_scenario() -> DOEScenario:
    """Set up the parametric study."""
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other for each sample.
    scenario = create_scenario(
        build_disciplines(),
        "f",
        build_design_space(),
        name="Study",
        scenario_type="DOE",
        formulation_name="DisciplinaryOpt",
    )
    return scenario


def execute_scenario(scenario: DOEScenario) -> None:
    """Evaluate the model for every combination of the values."""
    scenario.execute(algo_name="CustomDOE", samples=build_samples())


def main() -> None:
    """Run the study and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
