"""Sobieski BiLevel.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python sobieski_bilevel.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.problems.mdo.sobieski.disciplines import (
    SobieskiAerodynamics,
    SobieskiMission,
    SobieskiPropulsion,
    SobieskiStructure,
)
from gemseo.scenarios.mdo_scenario import MDOScenario


def build_disciplines() -> list[Discipline | MDOScenario]:
    """Create the disciplines and the sub-optimizations of System."""
    propulsion_optimizer = build_propulsion_optimizer_scenario()
    aerodynamics_optimizer = build_aerodynamics_optimizer_scenario()
    structure_optimizer = build_structure_optimizer_scenario()
    mission = SobieskiMission()
    mission.name = "Mission"
    return [propulsion_optimizer, aerodynamics_optimizer, structure_optimizer, mission]


def build_propulsion_optimizer_scenario() -> MDOScenario:
    """Set up PropulsionOptimizer, a sub-optimization of System."""
    propulsion = SobieskiPropulsion()
    propulsion.name = "Propulsion"
    design_space = create_design_space()
    design_space.add_variable("x_3", lower_bound=0.1, upper_bound=1.0, value=0.5)
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other at each iteration.
    scenario = create_scenario(
        [propulsion],
        "y_34",
        design_space,
        name="PropulsionOptimizer",
        formulation_name="DisciplinaryOpt",
    )
    scenario.add_constraint("g_3", constraint_type="ineq")
    # A nested scenario runs with the algorithm set here each time its
    # parent executes it.
    scenario.set_algorithm(algo_name="SLSQP", max_iter=30)
    return scenario


def build_aerodynamics_optimizer_scenario() -> MDOScenario:
    """Set up AerodynamicsOptimizer, a sub-optimization of System."""
    aerodynamics = SobieskiAerodynamics()
    aerodynamics.name = "Aerodynamics"
    design_space = create_design_space()
    design_space.add_variable("x_2", lower_bound=0.75, upper_bound=1.25, value=1.0)
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other at each iteration.
    scenario = create_scenario(
        [aerodynamics],
        "y_24",
        design_space,
        name="AerodynamicsOptimizer",
        maximize_objective=True,
        formulation_name="DisciplinaryOpt",
    )
    scenario.add_constraint("g_2", constraint_type="ineq")
    scenario.set_algorithm(algo_name="SLSQP", max_iter=30)
    return scenario


def build_structure_optimizer_scenario() -> MDOScenario:
    """Set up StructureOptimizer, a sub-optimization of System."""
    structure = SobieskiStructure()
    structure.name = "Structure"
    design_space = create_design_space()
    design_space.add_variable(
        "x_1",
        size=2,
        lower_bound=[0.1, 0.75],
        upper_bound=[0.4, 1.25],
        value=[0.25, 1.0],
    )
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other at each iteration.
    scenario = create_scenario(
        [structure],
        "y_11",
        design_space,
        name="StructureOptimizer",
        maximize_objective=True,
        formulation_name="DisciplinaryOpt",
    )
    scenario.add_constraint("g_1", constraint_type="ineq")
    scenario.set_algorithm(algo_name="SLSQP", max_iter=30)
    return scenario


def build_design_space() -> DesignSpace:
    """Define the variables the optimizer is allowed to change."""
    design_space = create_design_space()
    design_space.add_variable(
        "x_shared",
        size=6,
        lower_bound=[0.01, 30000.0, 1.4, 2.5, 40.0, 500.0],
        upper_bound=[0.09, 60000.0, 1.8, 8.5, 70.0, 1500.0],
        value=[0.05, 45000.0, 1.6, 5.5, 55.0, 1000.0],
    )
    return design_space


def build_scenario() -> MDOScenario:
    """Set up the optimization problem."""
    # BiLevel formulation: at each iteration, an MDA computes the coupling
    # variables, each sub-optimization improves its own design variables,
    # then a second MDA updates the couplings.
    scenario = create_scenario(
        build_disciplines(),
        "y_4",
        build_design_space(),
        name="System",
        maximize_objective=True,
        formulation_name="BiLevel",
        apply_cstr_tosub_scenarios=False,
    )
    scenario.add_constraint("g_1", constraint_type="ineq")
    scenario.add_constraint("g_2", constraint_type="ineq")
    scenario.add_constraint("g_3", constraint_type="ineq")
    return scenario


def execute_scenario(scenario: MDOScenario) -> None:
    """Run the COBYQA optimizer for at most 20 iterations."""
    scenario.execute(algo_name="COBYQA", max_iter=20)


def main() -> None:
    """Run the optimization and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
