"""Wing sizing.

Wing sizing: maximize the range by choosing the wing area and span. The weight of the
structure depends on the maneuver load computed by the aerodynamics, which depends on
the weight: an MDA solves this coupling.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python wing_sizing.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.disciplines.analytic import AnalyticDiscipline
from gemseo.scenarios.mdo_scenario import MDOScenario


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Optimizer."""
    aero = AnalyticDiscipline(
        {
            "drag": (
                "3000*area*(0.025 + (weight/(3000*area))**2/(3.1416*0.8*span**2/area))"
            ),
            "load_max": "2.5*weight",
        },
        name="Aero",
    )
    structure = AnalyticDiscipline(
        {"weight": "50000 + 500*area + 0.006*load_max*span**2/area"}, name="Structure"
    )
    performance = AnalyticDiscipline(
        {
            "range_km": "600*weight/drag*log(1 + 20000/weight)",
            "wing_loading": "weight/area",
        },
        name="Performance",
    )
    return [aero, structure, performance]


def build_design_space() -> DesignSpace:
    """Define the variables the optimizer is allowed to change."""
    design_space = create_design_space()
    design_space.add_variable("area", lower_bound=10.0, upper_bound=60.0, value=30.0)
    design_space.add_variable("span", lower_bound=8.0, upper_bound=30.0, value=15.0)
    return design_space


def build_scenario() -> MDOScenario:
    """Set up the optimization problem."""
    # MDF formulation: an MDA solves the coupling loop between
    # Aero and Structure (load_max, weight) at each iteration.
    scenario = create_scenario(
        build_disciplines(),
        "range_km",
        build_design_space(),
        name="Optimizer",
        maximize_objective=True,
        formulation_name="MDF",
    )
    scenario.add_constraint("wing_loading", constraint_type="ineq", value=3000.0)
    return scenario


def execute_scenario(scenario: MDOScenario) -> None:
    """Run the NLOPT_MMA optimizer for at most 100 iterations."""
    scenario.execute(algo_name="NLOPT_MMA", max_iter=100)


def main() -> None:
    """Run the optimization and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
