"""The demos of the Library: the example studies, opened as copies (SPEC § 7.6).

The demos are the scripts of ``examples/``, shipped in the package as
``gemseo_process_builder/demos``: a script is a demo when its docstring says
how to run it (``Run it with: python <its name>``), unlike the modules and
programs it uses. A demo in a folder of its own (an external code, several
modules) is copied with its folder.

A demo is never opened where it is installed: it is copied to a folder of the
user, where it can be changed and run; a copy made before is opened again.
"""

import ast
import re
import shutil
from dataclasses import dataclass
from pathlib import Path

PACKAGE = Path(__file__).resolve().parent.parent
"""The folder of the package."""

RUN_LINE = re.compile(r"^Run it with: python (\S+)$", re.MULTILINE)

IGNORED = shutil.ignore_patterns("__pycache__", "*.pyc", "models", "*.runs")
"""What is not copied with a demo: caches, trained models, runs."""


@dataclass(frozen=True)
class Demo:
    """A demo: its script, relative to the demos folder, and what it shows."""

    id: str
    title: str
    summary: str

    @property
    def in_folder(self) -> bool:
        """Whether the demo has a folder of its own, copied with it."""
        return "/" in self.id


def demos_folder() -> Path | None:
    """The demos: shipped in the package, or the examples of the repository."""
    for folder in (PACKAGE / "demos", PACKAGE.parent / "examples"):
        if folder.is_dir():
            return folder
    return None


def _demo(path: Path, folder: Path) -> Demo | None:
    try:
        docstring = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8")))
    except (SyntaxError, UnicodeDecodeError, OSError):
        return None
    run = RUN_LINE.search(docstring or "")
    if docstring is None or run is None or run.group(1) != path.name:
        return None
    paragraphs = [" ".join(part.split()) for part in docstring.split("\n\n")]
    details = [
        part
        for part in paragraphs[1:]
        if not part.startswith(("Generated by", "Run it with"))
    ]
    return Demo(
        id=path.relative_to(folder).as_posix(),
        title=paragraphs[0].removesuffix("."),
        summary=details[0] if details else "",
    )


def find_demos(folder: Path) -> list[Demo]:
    """The demos of a folder: its scripts, and those of its sub-folders."""
    paths = [*folder.glob("*.py"), *folder.glob("*/*.py")]
    demos = [_demo(path, folder) for path in sorted(paths)]
    return sorted(
        (demo for demo in demos if demo is not None),
        key=lambda demo: demo.title.lower(),
    )


def copy_demo(folder: Path, demo: Demo, copies: Path) -> Path:
    """Copy a demo to a folder of the user, unless it was copied before.

    Args:
        folder: The demos folder.
        demo: The demo.
        copies: The folder of the user receiving the copies.

    Returns:
        The script of the copy.
    """
    source = folder / demo.id
    target = copies / (source.parent.name if demo.in_folder else source.stem)
    script = target / source.name
    if script.is_file():
        return script  # Copied before: the changes of the user are kept.
    if demo.in_folder:
        shutil.copytree(source.parent, target, ignore=IGNORED, dirs_exist_ok=True)
    else:
        target.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, script)
    return script
