"""External code.

Generated by GEMSEO Process Builder 0.1.0 on 2026-09-26.
Run it with: python external_code.py
"""

from pathlib import Path

from gemseo import configure_logger, create_design_space, create_scenario
from gemseo.algos.design_space import DesignSpace
from gemseo.core.discipline import Discipline
from gemseo.scenarios.mdo_scenario import MDOScenario

from gemseo_process_builder.runtime.executable import ExecutableDiscipline

SOLVER_WRAPPER = Path(__file__).parent / "solver.gpbwrap.json"


def build_disciplines() -> list[Discipline]:
    """Create the disciplines of Optimizer."""
    # Solver runs an external code described by its wrapper.
    solver = ExecutableDiscipline.from_descriptor(SOLVER_WRAPPER)
    # External codes give no derivatives: they are approximated by finite
    # differences.
    solver.set_jacobian_approximation()
    return [solver]


def build_design_space() -> DesignSpace:
    """Define the variables the optimizer is allowed to change."""
    design_space = create_design_space()
    design_space.add_variable("x", lower_bound=-5.0, upper_bound=5.0, value=0.0)
    design_space.add_variable("y", lower_bound=-5.0, upper_bound=5.0, value=0.0)
    return design_space


def build_scenario() -> MDOScenario:
    """Set up the optimization problem."""
    # DisciplinaryOpt formulation: the disciplines are evaluated one after
    # the other at each iteration.
    scenario = create_scenario(
        build_disciplines(),
        "f",
        build_design_space(),
        name="Optimizer",
        formulation_name="DisciplinaryOpt",
    )
    scenario.add_constraint("g", constraint_type="ineq")
    return scenario


def execute_scenario(scenario: MDOScenario) -> None:
    """Run the SLSQP optimizer for at most 20 iterations."""
    scenario.execute(algo_name="SLSQP", max_iter=20)


def main() -> None:
    """Run the optimization and save its results next to this script."""
    configure_logger()
    scenario = build_scenario()
    execute_scenario(scenario)
    folder = Path(__file__).parent
    scenario.save_optimization_history(folder / "history.h5")
    scenario.to_dataset().to_csv(folder / "dataset.csv")


if __name__ == "__main__":
    main()
